In [1]:
from robosuite import Stack
import numpy as np
import imageio
import time
import IPython.display as display
from IPython.display import clear_output
from PIL import Image

In [4]:
env = Stack(robots="Panda", 
            controller_configs={
                "type": "OSC_POSE",
                "interpolation": "linear",
                "ramp_ratio": 0.6
            },
            use_camera_obs=True,
            camera_names=["agentview", "robot0_eye_in_hand"],  # Enable both cameras
            camera_heights=128,
            camera_widths=128,
            reward_shaping=True,
            has_renderer=False,
            has_offscreen_renderer=True,
            ignore_done=False,
            control_freq=20,
            render_gpu_device_id=0,)

In [10]:
action = np.random.rand(env.action_dim)

In [12]:
print(action.shape)

(7,)


In [13]:
env.step(action)

(OrderedDict([('robot0_joint_pos_cos',
               array([ 0.99920392,  0.98704623,  0.99993516, -0.87610735,  0.99999528,
                      -0.98310715,  0.6919312 ])),
              ('robot0_joint_pos_sin',
               array([-0.03989394,  0.16043607, -0.01138796, -0.48211608,  0.00307205,
                       0.18303098,  0.72196345])),
              ('robot0_joint_vel',
               array([ 0.00492123,  0.04599019,  0.03576567,  0.01845567,  0.02143275,
                      -0.01301778, -0.00299891])),
              ('robot0_eef_pos',
               array([-0.10310946, -0.02398399,  1.02246841])),
              ('robot0_eef_quat',
               array([ 0.99618604, -0.03725756,  0.07888146,  0.00172418])),
              ('robot0_gripper_qpos', array([ 0.020833  , -0.02082979])),
              ('robot0_gripper_qvel',
               array([-2.29656274e-06,  1.60731049e-03])),
              ('agentview_image',
               array([[[247, 246, 242],
                    